version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8001:8001"
    networks:
      - dockless-network  

networks:
  dockless-network:
    driver: bridge  