version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dockless-network  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Enable access docker on host machine
      - ./nginx.conf:/app/nginx.conf 
    networks:
      - dockless-network  
    depends_on:
      - nginx
      - redis
    env_file:
      - ./api/.env
  redis:
    image: redis:7.2.7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dockless-network

networks:
  dockless-network:
    driver: bridge  