version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dockless-network  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app # enable development with hot reload 
      - /var/run/docker.sock:/var/run/docker.sock # enable container to use docker on host machine
      - ./nginx.conf:/app/nginx.conf # enable 
    networks:
      - dockless-network  
    depends_on:
      - nginx
      - redis
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dockless-network

networks:
  dockless-network:
    driver: bridge  